export const meta = {
  name: 'company-brain-sweep',
  description: 'Research sweep: Garry Tan company-brain talk vs RAG vs fruit-fly brain work; 14 dimensions + completeness critic',
  phases: [
    { title: 'Sweep', detail: '14 parallel Opus 5 researchers, one dimension each', model: 'opus' },
    { title: 'Critic', detail: 'completeness critic over all summaries', model: 'opus' },
  ],
}

const DIR = '/Users/stephen/Cookies/company-brain-research'
const TODAY = '2026-09-10'

const PREAMBLE = `You are a research worker (Claude Opus 5) inside a multi-agent research project. Today is ${TODAY}.
Research folder: ${DIR}
  - ${DIR}/sources/transcript_eBUyTS7SzV4.txt  (full timestamped transcript of the talk)
  - ${DIR}/checkpoints/00-plan.md               (orchestrator's summary of the talk + open questions — READ THIS FIRST)
  - ${DIR}/findings/                            (write your report here)

Context: The talk is "Every company should have a Brain" by Garry Tan (President of Y Combinator), AI Engineer channel, published 2026-07-16.
Thesis: a "company brain" = library + librarian; retrieval (RAG) is only the primitive; the product is curation, provenance,
hot-vs-cold memory, contradiction arbitration, and "skillifying" every piece of work. His open-source project is GBrain
("Postgres for agents"), which "loves OpenClaw / Hermes agent".
The user asks: (a) does this relate to RAG? (b) can it be combined with "the recently published fruit fly brain work"?
(c) what interesting projects are built around these ideas?

Tools: use ToolSearch to load WebSearch and WebFetch, then search/fetch aggressively. For GitHub repos prefer
\`curl -sL https://raw.githubusercontent.com/<owner>/<repo>/<branch>/README.md\` or \`gh api\` via Bash. Read actual sources; do not rely on memory alone —
your training data may predate mid-2026 developments. Record the exact URL for every fact.

Deliverable (BOTH are required):
1. Write a thorough markdown report to ${DIR}/findings/<your key>.md (use Bash heredoc or the Write tool). Structure: TL;DR (5 bullets),
   detailed findings with inline source URLs, a "Relevance to company-brain / RAG / fruit-fly question" section, open questions, and a
   "Sources" list. Be concrete: names, dates, numbers, repo URLs, paper DOIs/arXiv IDs. 800-2500 words.
2. Return the structured summary via the StructuredOutput tool: 5-10 key_insights (each one sentence, decision-relevant),
   key_facts with source_url and confidence (high/medium/low), open_questions, and report_path.
Do not pad. Do not fabricate URLs — if you cannot verify something, mark confidence low and say so.`

const SUMMARY_SCHEMA = {
  type: 'object',
  properties: {
    key_insights: { type: 'array', items: { type: 'string' } },
    key_facts: { type: 'array', items: { type: 'object', properties: {
      claim: { type: 'string' }, source_url: { type: 'string' }, confidence: { type: 'string' } },
      required: ['claim', 'source_url', 'confidence'] } },
    open_questions: { type: 'array', items: { type: 'string' } },
    report_path: { type: 'string' },
  },
  required: ['key_insights', 'key_facts', 'open_questions', 'report_path'],
}

const DIMS = [
  { key: 'talk-analysis', prompt: `Key: talk-analysis. Read the FULL transcript at ${DIR}/sources/transcript_eBUyTS7SzV4.txt (auto-captions; fix obvious mis-transcriptions such as "G brain"=GBrain, "open claw"=OpenClaw, "Claude Coder Codex"=Claude Code or Codex, "e-vals"=evals). Produce a rigorous structured analysis: (1) the argument in order with timestamps; (2) every concrete concept/term with his definition (skill file, resolver table, filing rules, trigger evals, latent vs deterministic space, working memory / three books, library + librarian, hot memory vs cold reference, provenance, contradiction checks, skillify, one-off work); (3) every quantitative claim with timestamp; (4) every named product/company/person; (5) his explicit answer to "this is just RAG" quoted verbatim with timestamp; (6) what he says the greenfield opportunity is; (7) the strongest and weakest parts of the argument. Also fetch the YouTube page description/timestamps for cross-check.` },
  { key: 'garry-tan-ecosystem', prompt: `Key: garry-tan-ecosystem. Map Garry Tan's public artifacts around this talk: the GBrain GitHub repo (find the real URL — search "gbrain garrytan github"), his "skillify it" post on X/blog, OpenClaw (what is it — an agent harness? by whom?), Hermes agent (Nous Research? or other?), and any talks/podcasts/blog posts from 2026 where he elaborates the "company brain" concept. For each: URL, date, one-paragraph summary, what it adds beyond the talk. Also find press/community reaction to the talk and to the "400X" claim (he says he "got torn apart on the internet"). Include the 80,000-markdown-file epilepsy story if it is public.` },
  { key: 'gbrain-architecture', prompt: `Key: gbrain-architecture. Deep-dive the GBrain repository (search "gbrain github Garry Tan" / "Postgres for agents"; confirm the real repo). Read README, docs, schema/migrations, and core source files via raw.githubusercontent.com or gh api. Document: storage model (Postgres? pgvector? markdown?), ingestion pipeline, how retrieval works (embeddings, hybrid search, reranking, graph links?), hot vs cold memory, provenance fields, contradiction handling, the "librarian" logic, harness integration (Claude Code / OpenClaw / Hermes / MCP?), skills format, evals. Quote code/config where useful. Note stars, license, last commit, contributor count. If the repo does not exist or is private, say so clearly and document what IS public.` },
  { key: 'rag-taxonomy', prompt: `Key: rag-taxonomy. Answer precisely: how does a "company brain" relate to RAG? Build a taxonomy: naive RAG → advanced RAG (hybrid, rerank, query rewriting) → GraphRAG (Microsoft, LightRAG) → agentic RAG → agent memory systems (episodic/semantic/procedural; hot vs cold; write-side curation) → "brain"/second-brain systems. For each layer: what problem it solves, canonical papers/repos (with URLs), and which of Tan's requirements it covers (what gets written, enrichment/linking, hot/cold promotion, provenance, contradiction arbitration, librarian/pruning, skills as procedural memory). Conclude with a crisp answer: is the company brain "just RAG"? Where exactly does it go beyond, and which existing systems already implement each beyond-RAG feature. Cite surveys from 2024-2026 (e.g., RAG surveys, agent memory surveys).` },
  { key: 'memory-systems-landscape', prompt: `Key: memory-systems-landscape. Survey the agent-memory / second-brain open-source and commercial landscape as of ${TODAY}: mem0, Letta (MemGPT), Zep/Graphiti, Cognee, A-MEM, MemoryBank, Memary, Khoj, Supermemory, Mnemo/other, LangMem, Anthropic Claude Code memory & Skills, OpenAI memory, Google's, plus any 2026 newcomers (search "agent memory layer 2026", "company brain open source", "second brain for agents"). For each: URL, GitHub stars (fetch via gh api), core design (vector / graph / markdown / SQL), write-side curation features, hot/cold tiers, provenance, contradiction handling, benchmark results (LoCoMo, LongMemEval etc.). Produce a comparison table. Highlight which are closest to Tan's "library + librarian" spec.` },
  { key: 'flyfly-recent-identification', prompt: `Key: flyfly-recent-identification. The user refers to "the recently published fruit fly brain work" (as of ${TODAY}) without naming it. Identify ALL plausible referents and rank them by likelihood of being what a tech-savvy person means in Sep 2026. Search news and arXiv/bioRxiv/Nature for the last ~12 months: e.g. FlyWire whole-brain connectome (Nature, Oct 2024) and follow-ups; whole-brain simulations of the fly (Shiu et al. 2024; any 2025-2026 successors, e.g. Eon Systems, Janelia, Google); "male CNS connectome" / "BANC" brain-and-nerve-cord connectome (2025?); fruit-fly-inspired AI/ML papers (FlyHash LSH, "fruit fly word embeddings", mushroom-body-inspired memory, sparse expansion); anything from June-Sept 2026 specifically. For each candidate: title, authors, venue, date, URL, one-paragraph summary, and why someone would connect it to "company brain"/RAG. Give a ranked verdict with reasoning.` },
  { key: 'flywire-connectome-simulation', prompt: `Key: flywire-connectome-simulation. Deep-dive the fruit fly connectome and whole-brain simulation line of work: FlyWire (Dorkenwald et al., Nature 2024; ~139k neurons, ~50M synapses), Schlegel et al. 2024 cell types, Shiu et al. 2024 "A Drosophila computational brain model reveals sensorimotor processing" (leaky integrate-and-fire on the connectome), Lappalainen et al. 2024 (connectome-constrained deep network of the visual system), BANC / male CNS (2025), and any 2025-2026 successors (search "whole brain simulation fruit fly 2026", "Eon Systems fly", "virtual fly brain"). Explain what these actually enable computationally, what data/tools are open (Codex, neuprint, FlyWire APIs), and — critically — evaluate honestly whether and how any of it could be applied to an AI "company brain" / RAG system (e.g., connectome-derived architectures, routing motifs, memory circuits) vs. where the analogy is only metaphorical.` },
  { key: 'flyhash-sparse-retrieval', prompt: `Key: flyhash-sparse-retrieval. Deep-dive fruit-fly-olfaction-inspired algorithms for similarity search and memory, the most direct bridge to RAG: Dasgupta, Stevens & Navlakha 2017 Science "A neural algorithm for a fundamental computing problem" (FlyHash LSH: random sparse expansion + winner-take-all); Dasgupta et al. 2018 "A neural data structure for novelty detection" (fly Bloom filter); Ryali et al. 2020 "Bio-inspired hashing (BioHash)"; Liang et al. ICLR 2021 "Can a fruit fly learn word embeddings?"; sparse binary embeddings / "FlyVec"; any 2023-2026 follow-ups applying fly-inspired hashing to LLM retrieval, embeddings, or agent memory (search arXiv: "fly hashing retrieval 2025", "mushroom body inspired memory transformer", "sparse expansion winner take all retrieval"). For each: method, results vs baselines (e.g., vs LSH/HNSW/dense), open implementations (URLs), and a concrete assessment of whether it could serve as the "librarian's" index in a company brain: pros (cheap, streaming, novelty detection, binary/sparse), cons (recall vs dense embeddings at scale).` },
  { key: 'mushroom-body-memory-models', prompt: `Key: mushroom-body-memory-models. The fly mushroom body is a canonical associative-memory circuit (Kenyon cells sparse code; dopamine-gated plasticity at KC→MBON synapses; compartments for valence; forgetting via dopamine; memory consolidation short-term → long-term). Survey computational models of it (e.g., Aso et al. 2014; Hige; Modi, Shuai & Turner 2020 review; Springer/Nawrot models; "Drosophila mushroom body model deep learning 2025/2026") and any work using it as a model for AI memory: sparse coding, compartmentalized valence, active forgetting, hot/cold consolidation. Map each mechanism to Tan's brain requirements: hot memory vs cold reference (consolidation), pruning (active forgetting), provenance/valence tags (compartments), novelty detection. Be honest about which mappings are deep vs superficial. Include any 2026 papers.` },
  { key: 'neuro-inspired-rag', prompt: `Key: neuro-inspired-rag. Survey neuroscience-inspired retrieval/memory for LLMs other than fly-specific work, to give the user a wider bridge: HippoRAG / HippoRAG 2 (hippocampal indexing theory + PPR over KG), complementary learning systems (CLS) for agent memory, modern Hopfield networks (Ramsauer 2020; attention = Hopfield retrieval), sparse distributed memory (Kanerva) links to transformers, memory consolidation/replay in continual learning, "Titans"/Google memory papers (2025), MemOS / memory operating systems (2025), "cognitive architectures for language agents" (CoALA), and 2026 work. For each: URL, what biological principle it borrows, measured benefit, open code. Conclude with which principles are ready for a production company brain today.` },
  { key: 'context-engineering-skills', prompt: `Key: context-engineering-skills. Document the "context engineering" and "skills" side of the talk as practiced in 2025-2026: Anthropic's "Effective context engineering for AI agents" post, Claude Code CLAUDE.md / memory / Agent Skills spec (skills as markdown with frontmatter; progressive disclosure), resolver tables ("when you need X, load X.md"), OpenAI Codex AGENTS.md, Cursor rules, MCP resources; the "latent vs deterministic space" split (compare with "code as tool" / program-aided LMs / "state must not live in the context window"); evals as "performance reviews" (trigger evals: does the right file get loaded?). Find the "skillify it" skill file and describe its mechanics. Give concrete, copyable patterns and cite URLs. Assess where Tan's org-chart metaphor (skill=employee, resolver=org chart, filing rules=process, evals=reviews) is accurate vs strained.` },
  { key: 'memory-hygiene', prompt: `Key: memory-hygiene. Tan says the primitive is "memory + hygiene": provenance per fact, contradiction checks when new info collides with old, a librarian (human+agent) whose job is pruning; failure modes = garbage dump with great search, stale fact with total confidence, bad skill encodes bad process forever. Research the state of the art and practice for each: provenance/attribution in RAG (citation, source tracking, W3C PROV), knowledge-conflict detection & resolution in LLMs (papers 2023-2026: "knowledge conflicts survey", temporal validity, "stale fact"), memory decay/forgetting policies (Ebbinghaus-style, mem0/Zep/Graphiti temporal edges, invalidation), memory poisoning / prompt-injection via memory (security), skill/process drift and eval-gated skill updates. For each: best available technique, open implementations, and a recommended concrete policy for a company brain. Cite URLs.` },
  { key: 'skeptic-claims', prompt: `Key: skeptic-claims. Be the skeptic in the third row. Fact-check and stress-test the talk's quantitative and factual claims: "400X" personal output (8X floor, 80X middle) and how he measured; Winter 25 batch 25% of companies 95% AI-generated code (source: Jared Friedman / YC statements March 2025?); "94 companies crossed $100M revenue"; Emergent(ce?) "nine figures ARR in 8 months, 15 people at $15M ARR"; "Retail"(?) at $60M with 40 people (which company — maybe a mis-transcription); "1M tokens ≈ 1000 pages ≈ 3 Harry Potter books"; "7±2" (Miller 1956 vs Cowan 2001 "4±1"); "220,000 pages"; revenue per head "never existed before" (compare Instagram/WhatsApp/Nvidia). Also evaluate the conceptual claims: is "company brain" materially different from RAG + memory systems already shipping? Are the failure modes he lists solved by his own tool? Find published critiques of the talk/GBrain/"vibe org" thesis. Rate each claim: verified / plausible / unverified / contradicted, with URLs.` },
  { key: 'projects-built-on-ideas', prompt: `Key: projects-built-on-ideas. The user says "I've seen many interesting projects built around these ideas". Find them: projects explicitly inspired by GBrain / "company brain" / "second brain for agents" / "skillify" (search GitHub, X, Hacker News, Product Hunt, YC S26/F26 batch descriptions: "company brain", "organizational memory for agents", "agent memory layer", "AI-native company OS"); projects combining fruit-fly-brain ideas with LLM retrieval or memory (FlyHash in vector DBs, "fly" hashing libraries, connectome-inspired agent architectures); Obsidian/markdown-vault-based agent brains; OpenClaw/Hermes ecosystem projects. For each: URL, stars/traction, what it does, how it relates to the talk, maturity. Aim for 20-30 projects; group them; flag the 5 most worth the user's attention and why. Also list YC companies pursuing "brain" products.` },
]

phase('Sweep')
log(`Launching ${DIMS.length} Opus 5 researchers`)
const results = await parallel(DIMS.map(d => () =>
  agent(`${PREAMBLE}\n\n=== YOUR DIMENSION ===\n${d.prompt}`, { label: `sweep:${d.key}`, phase: 'Sweep', model: 'opus', schema: SUMMARY_SCHEMA })
    .then(r => r ? { key: d.key, ...r } : null)
))
const ok = results.filter(Boolean)
const failed = DIMS.map(d => d.key).filter(k => !ok.some(r => r.key === k))
log(`Sweep done: ${ok.length}/${DIMS.length} succeeded${failed.length ? '; FAILED: ' + failed.join(', ') : ''}`)

phase('Critic')
const digest = ok.map(r => `## ${r.key}\nInsights:\n- ${r.key_insights.join('\n- ')}\nOpen questions:\n- ${r.open_questions.join('\n- ')}`).join('\n\n')
const critic = await agent(`${PREAMBLE}\n\n=== YOUR ROLE: completeness critic ===\nKey: completeness-critic. Below are the summaries from ${ok.length} researchers (full reports in ${DIR}/findings/*.md — read any you need). Failed dimensions (no output): ${failed.join(', ') || 'none'}.
Ask: what is MISSING to answer the user's three questions decisively? Which claims are unverified or contradictory across reports? Which "fruit fly" referent is still ambiguous? Which projects were probably missed? What would a domain expert (RAG engineer, computational neuroscientist, YC founder) object to? Produce (a) a ranked list of gaps with a concrete follow-up task each (one paragraph, assignable to one agent), (b) cross-report contradictions with file references, (c) the 10 claims most worth adversarial verification next round. Write the full critique to ${DIR}/findings/completeness-critic.md and return the structured summary (key_insights = top gaps; key_facts = contradictions; open_questions = the 10 claims to verify).\n\n=== SUMMARIES ===\n${digest}`,
  { label: 'critic', phase: 'Critic', model: 'opus', schema: SUMMARY_SCHEMA })

return { sweep: ok, failed, critic }